# Generated by Django 4.2.4 on 2023-09-04 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticeboard',
            name='user',
        ),
    ]
